feat: :sparkles: Adds keys state to allow toggle keys
willianrod/ODeck pull request #30
Opened 2023-08-22 22:30 UTC by IsmaelEzequiel

Hi, adds active state to buttons #25

2023-08-23 01:21 UTC, willianrod requested changes
We could reuse the same style already applied when dragging over a key

2023-08-23 14:44 UTC, IsmaelEzequiel commented on src/renderer/components/key/index.tsx
> +        }
Sure, I'll make the changes

2023-08-24 01:02 UTC, IsmaelEzequiel commented
@willianrod fixed!

2023-08-24 03:46 UTC, willianrod approved these changes
LGTM!

2023-08-24 03:47 UTC, merged

2023-08-24 03:56 UTC, willianrod commented
@IsmaelEzequiel thanks for your contribution. Hope to see you again ;)